librechat:
  existingConfigYaml: "librechat-config"
  configEnv:
    ALLOW_REGISTRATION: "true"

mongodb:
  image:
    tag: latest
  persistence:
    enabled: false

meilisearch:
  persistence:
    enabled: false
